### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jonkerz** [jonkerz/kingscourt#1]
- [x] Setup production email account
- [x] Restore Disqus
- [x] Fix footer
- [x] www to no-www
- [x] Add Travis CI
